apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    #app: devsecops
    app: bkimminich
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bkimminich
  strategy: {}
  template:
    metadata:
      labels:
        app: bkimminich
    spec:
      containers:
      - image: replace
        name: devsecops-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bkimminich
  name: devsecops-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bkimminich
  type: NodePort