---
- name: playbook
  hosts: atlanta
  become: true
  tasks:
    - name: Install NGINX App Protect WAF
      ansible.builtin.include_role:
        name: ansible-role-nginx-app-protect
      vars:
        nginx_app_protect_license:
          certificate: /etc/ssl/nginx-repo.crt
          key: /etc/ssl/nginx-repo.key
        nginx_app_protect_remove_license: false
        nginx_app_protect_waf_install_signatures: true
        nginx_app_protect_waf_install_threat_campaigns: true
        nginx_app_protect_timeoutstartsec: 180